add a check for known hosts

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -61,7 +61,8 @@ jobs:
       - name: Read known hosts
         run: |
           cd ${{ github.event.repository.name }}
-          $ [ -f "infrastructure/known-hosts" ] || { echo "infrastructure/known-hosts missing" ; exit 1 ;}
+          ls -lha infrastructure
+          [ -f "infrastructure/known-hosts" ] || { echo "infrastructure/known-hosts missing" ; exit 1 ;}
           echo "KNOWN_HOSTS<<EOF" >> $GITHUB_ENV
           sed -i -e '$a\' ./infrastructure/known-hosts
           cat ./infrastructure/known-hosts >> $GITHUB_ENV
